const express = require('express')
const app = express()
const authMiddleware = require('./middleware/auth.middleware')
app.use(authMiddleware)
app.get('/', (req, res) => {
  res.status(500).json({ message: "Error" })
  res.send("This is expressJs")
})
const adminRouter = require('./routes/admin')
app.use('/admin', adminRouter)
app.listen(3000)
